language: r
sudo: false
cache: packages


r_binary_packages:
  - R6

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'devtools::install();library(lazytensor);library(methods);devtools::test()'
  - Rscript -e 'library(covr);coveralls()'
