language: r
sudo: false
cache: packages

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=false

r_binary_packages:
  - R6
  - roxygen2

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'devtools::install();library(lazytensor);library(methods);devtools::test()'
  - Rscript -e 'library(covr);coveralls()'
